image:
  repository: stalwartlabs/mail-server
  pullPolicy: IfNotPresent
  tag: ''

service:
  type: NodePort
  ports:
    http: 8080
    https: 443
    smtp: 25
    submission: 587
    smtps: 465
    imap: 143
    imaps: 993
    sieve: 4190

ingress:
  enabled: false
  className: ''
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

traefik:
  enabled: false
  #host: "mail.example.com"
  ports:
    http: websecure
    imaps: imaps
    smtps: smtps

## Persist configuration to a persistent volume
persistence:
  # persistence.enabled - Should disk persistence be enabled
  enabled: false
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  existingClaim: ''
  storageClass: ''
  accessMode: ReadWriteOnce
  size: 10Gi
  mountPath: /opt/stalwart-mail

replicaCount: 1
