apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stalwart-mail.fullname" . }}
  labels: {{- include "stalwart-mail.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "stalwart-mail.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "stalwart-mail.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: stalwart-mail
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 443
            - containerPort: 25
            - containerPort: 587
            - containerPort: 465
            - containerPort: 143
            - containerPort: 993
            - containerPort: 4190
          volumeMounts:
            - name: stalwart-volume
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: stalwart-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "stalwart-mail.fullname" .) }}
