{{- if .Values.traefik.enabled }}
{{- range $port, $entryport := .Values.traefik.ports }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "stalwart-mail.fullname" $ }}-{{ $port }}
spec:
  entryPoints:
    - {{ $entryport }}
  routes:
    {{- range $index, $host := $.Values.traefik.hosts }}
    - match: HostSNI(`{{ $host }}`)
      services:
        - name: {{ include "stalwart-mail.fullname" $ }}
          port: {{ $port }}
    {{- end }}
  tls:
    secretName: {{ $.Values.traefik.tlsSecretName }}
{{- end }}
{{- end }}
